global:
  scrape_interval: 15s # Default scrape interval for all targets.
  evaluation_interval: 15s # Default evaluation interval for all rules.
  scrape_timeout: 10s # Timeout for scraping metrics from targets.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager service endpoint (replace with your actual Alertmanager endpoint)
            - alertmanager:9093

# Rule files to define alerting rules
rule_files:
  - "alert.rules.yml"

# Scrape configuration for Socks Shop application
scrape_configs:
  - job_name: 'socks_shop'
    metrics_path: /metrics
    static_configs:
      - targets:
          - <SOCKS_SHOP_APP_SERVICE>:<PORT>
          # Replace <SOCKS_SHOP_APP_SERVICE> with the service name of your Socks Shop app
          # Replace <PORT> with the port exposing metrics (typically 8080)

  # Scrape configuration for Kubernetes components
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs
